version = 1

[[annotations]]
path = [
  "dist/**",
  ".git/**",
  "pnpm-lock.yaml",
  "coverage/**",
  "reports/**",
  "node_modules/**",
  ".husky/_/husky.sh",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Osman Aslan"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "apps/container/Dockerfile",
  ".github/workflows/**",
  ".github/dependabot.yml",
  ".github/CODEOWNERS",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Osman Aslan"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "LICENSES/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Osman Aslan"
SPDX-License-Identifier = "LicenseRef-REUSE"
