/** @type {import("@stryker-mutator/core").PartialStrykerOptions} */
export default {
  packageManager: "pnpm",
  testRunner: "vitest",
  plugins: ["@stryker-mutator/vitest-runner"],
  vitest: {
    configFile: "vitest.config.ts",
  },
  testFiles: ["tests/unit/**/*.test.ts", "tests/property/**/*.test.ts", "tests/snapshot/**/*.test.ts"],
  mutate: [
    "src/core/**/*.ts",
    "!src/core/context.ts",
    "!src/core/result.ts",
    "src/kicad/sexpr.ts",
    "src/kicad/pcb.ts",
    "src/kicad/schematic.ts",
    "src/kicad/schematic-graph.ts",
    "src/kicad/jobset.ts",
    "src/kicad/variants.ts",
    "src/rules/bom/lifecycle.ts",
    "src/rules/bom/variant-consistency.ts",
    "src/rules/design/**/*.ts",
    "src/rules/manufacturing/fiducials.ts",
    "src/rules/manufacturing/jobset-outputs.ts",
    "src/rules/manufacturing/layer-stackup.ts",
    "src/rules/manufacturing/outputs-present.ts",
    "src/rules/manufacturing/position-coverage.ts",
    "src/rules/manufacturing/shared.ts",
    "src/rules/manufacturing/tooling-holes.ts",
    "src/rules/pinmap/net-label.ts",
    "src/rules/pinmap/shared.ts",
    "src/rules/release/version-format.ts",
    "!src/**/*.d.ts",
    "!src/**/types.ts",
    "!src/**/*.types.ts",
    "!src/generated/**",
  ],
  thresholds: {
    high: 85,
    low: 80,
    break: 75,
  },
  reporters: ["html", "clear-text", "json"],
  htmlReporter: {
    fileName: "reports/mutation/index.html",
  },
  jsonReporter: {
    fileName: "reports/mutation/report.json",
  },
  coverageAnalysis: "perTest",
  ignoreStatic: true,
  timeoutMS: 10000,
  concurrency: 4,
};
