import { readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { readPnpmLicenseReport } from "./lib/pnpm-licenses.mjs";

const OUTPUT_FILE = "NOTICE";
const HOST_NATIVE_PACKAGE_PATTERNS = Object.freeze([
  /^@biomejs\/cli-/,
  /^@esbuild\//,
  /^@oxc-parser\/binding-/,
  /^@oxc-resolver\/binding-/,
  /^@rolldown\/binding-/,
  /^lightningcss-/,
]);

/** Read pnpm-lock.yaml to find packages with platform constraints (os:/cpu:). */
function readLockfilePlatformPackages(root) {
  const lockfilePath = path.join(root, "pnpm-lock.yaml");
  const content = readFileSync(lockfilePath, "utf8");
  const lines = content.split("\n");

  const platformPackages = new Set();
  let currentName = null;
  let hasOsOrCpu = false;

  for (const line of lines) {
    // Package entry: two spaces, single-quoted name@version':
    const pkgMatch = line.match(/^ {2}'(.+)@(.+)':\s*$/);
    if (pkgMatch) {
      if (currentName !== null && hasOsOrCpu) {
        platformPackages.add(currentName);
      }
      currentName = pkgMatch[1];
      hasOsOrCpu = false;
      continue;
    }

    if (currentName !== null) {
      if (/^\s{4}os:/.test(line) || /^\s{4}cpu:/.test(line)) {
        hasOsOrCpu = true;
      }
      if (line.trim() === "") {
        if (hasOsOrCpu) platformPackages.add(currentName);
        currentName = null;
        hasOsOrCpu = false;
      }
    }
  }

  // Handle last entry
  if (currentName !== null && hasOsOrCpu) {
    platformPackages.add(currentName);
  }

  return platformPackages;
}

const platformPackages = readLockfilePlatformPackages(process.cwd());

export async function main(root = process.cwd(), options = {}) {
  const report = await readPnpmLicenseReport(root, ["--json"]);
  const notice = renderNotice(report);
  const noticePath = path.join(root, OUTPUT_FILE);

  if (options.check) {
    const current = await readFile(noticePath, "utf8");
    if (current !== notice) {
      throw new Error("NOTICE is out of date. Run `corepack pnpm run notice`.");
    }
    return;
  }

  await writeFile(noticePath, notice);
}

export function renderNotice(report) {
  const sections = licenseSections(report);
  const lines = [
    "# BoardReadyOps Third-Party Notices",
    "",
    "BoardReadyOps itself is licensed under MIT; see `LICENSE`.",
    "",
    "Generated from `pnpm licenses list --json`.",
    "Do not edit this file by hand; run `corepack pnpm run notice`.",
    "",
    "## KiCad Container Image",
    "",
    "Container image redistributes KiCad under GPL terms.",
    "The image preserves the KiCad package license text at `/usr/share/doc/boardreadyops/LICENSE-KICAD` and the package notices under `/usr/share/doc/kicad/`.",
    "",
    "## npm Dependency Notices",
    "",
  ];

  if (sections.length === 0) {
    lines.push("No npm dependency license notices were reported by pnpm.", "");
    return finalizeNotice(lines);
  }

  for (const section of sections) {
    lines.push(`## ${section.license}`, "");
    for (const item of section.packages) {
      lines.push(`- ${packageVersions(item)}`);
      if (item.description) {
        lines.push(`  - Description: ${item.description}`);
      }
      if (item.homepage) {
        lines.push(`  - Homepage: ${item.homepage}`);
      }
    }
    lines.push("");
  }

  return finalizeNotice(lines);
}

function finalizeNotice(lines) {
  return `${lines.join("\n").trimEnd()}\n`;
}

function licenseSections(report) {
  return Object.entries(report)
    .map(([license, packages]) => ({
      license,
      packages: packages
        .filter((item) => !isHostNativePackage(item.name))
        .map((item) => ({
          ...item,
          versions: [...(item.versions ?? [])].sort(compareText),
        }))
        .sort(
          (left, right) =>
            compareText(left.name, right.name) || compareText(left.versions[0] ?? "", right.versions[0] ?? ""),
        ),
    }))
    .sort((left, right) => compareText(left.license, right.license));
}

function isHostNativePackage(name) {
  return HOST_NATIVE_PACKAGE_PATTERNS.some((pattern) => pattern.test(name)) || platformPackages.has(name);
}

function packageVersions(item) {
  return (item.versions ?? []).map((version) => `\`${item.name}@${version}\``).join(", ");
}

function compareText(left, right) {
  return left.localeCompare(right, "en", { numeric: true });
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  await main(process.cwd(), { check: process.argv.includes("--check") });
}
