import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import * as yaml from "js-yaml";
import {
  compareSeries,
  compareVersion,
  hasFlag,
  objectValue,
  optionValue,
  parseSeries,
  readJson,
  stringArray,
  stringRecord,
  stringValue,
} from "./compatibility-utils.mjs";

const DEFAULT_COMPATIBILITY_PATH = "docs/compatibility.yaml";
const DEFAULT_SUPPORT_MATRIX_PATH = "docs/support-matrix.md";
const NODE_RELEASE_INDEX_URL = "https://nodejs.org/dist/index.json";
const KICAD_TAGS_URL =
  "https://gitlab.com/api/v4/projects/kicad%2Fcode%2Fkicad/repository/tags?per_page=100&order_by=updated&sort=desc";

export function renderSupportMatrix(input) {
  const config = normalizeCompatibilityConfig(input);
  const lines = [
    "<!-- This file is generated by `pnpm run compatibility:docs`; edit `docs/compatibility.yaml`. -->",
    "",
    "# Support Matrix",
    "",
    "BoardReadyOps compatibility is defined in `docs/compatibility.yaml` and rendered here for humans.",
    "",
    "## KiCad",
    "",
    `Minimum supported KiCad: **${config.kicad.minimum}**. Recommended KiCad line: **${config.kicad.recommended}**. Latest verified patch: **${config.kicad.latestVerified}**.`,
    "",
    "| Runtime | Version | Status | Latest verified | Notes |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const version of kicadMatrixVersions(config)) {
    const status = kicadSupportStatus(config, version);
    lines.push(
      `| KiCad | ${version} | ${status} | ${kicadLatestVerifiedCell(config, version)} | ${markdownCell(
        kicadNote(config, version),
      )} |`,
    );
  }

  lines.push(
    "",
    "## Node.js",
    "",
    `Minimum supported Node.js: **${config.node.minimumVersion}**. Recommended Node.js major: **${config.node.recommended}**.`,
    "",
    "| Runtime | Version | Status | Tested latest | Policy |",
    "| --- | --- | --- | --- | --- |",
  );

  for (const version of config.node.supported) {
    const status = nodeSupportStatus(config, version);
    lines.push(
      `| Node.js | ${version} | ${status} | ${config.node.tested[version] ?? ""} | ${markdownCell(
        config.node.policy[version] ?? "",
      )} |`,
    );
  }

  for (const version of config.node.current) {
    lines.push(
      `| Node.js | ${version} | Current, not supported |  | ${markdownCell(config.node.policy[version] ?? "")} |`,
    );
  }

  lines.push(
    "",
    "## CycloneDX HBOM",
    "",
    "| Contract | Version | Status | Validation |",
    "| --- | --- | --- | --- |",
    `| CycloneDX JSON | ${config.cyclonedx.specVersion} | Pinned HBOM contract | ${markdownCell(
      config.cyclonedx.schemaUrl,
    )} |`,
    `| Repository HBOM schema | ${config.cyclonedx.hbomSchema} | CI validated | ${markdownCell(
      config.cyclonedx.validation,
    )} |`,
    "",
    "## Drift Detection",
    "",
    "The scheduled `compatibility-drift` workflow compares this matrix with the Node.js release index, KiCad GitLab tags, and the pinned CycloneDX schema. It opens a GitHub issue when a documented runtime, hardware-toolchain line, or HBOM contract needs review.",
  );

  return `${lines.join("\n")}\n`;
}

export function findCompatibilityDrift(input, sources) {
  const config = normalizeCompatibilityConfig(input);
  return {
    kicad: findKicadDrift(config, sources.kicadReleases ?? []),
    node: findNodeDrift(config, sources.nodeReleases ?? []),
    cyclonedx: findCycloneDxDrift(config, sources.cycloneDxSchema),
  };
}

export function buildDriftReport(drift) {
  const hasDrift = drift.kicad.length > 0 || drift.node.length > 0 || drift.cyclonedx.length > 0;
  if (!hasDrift) {
    return [
      "# No Compatibility Drift Detected",
      "",
      "`docs/compatibility.yaml` still matches the checked KiCad, Node.js, and CycloneDX release sources.",
    ].join("\n");
  }

  const lines = [
    "# Compatibility Matrix Drift Detected",
    "",
    "`docs/compatibility.yaml` needs review against the current upstream release sources.",
  ];

  if (drift.kicad.length > 0) {
    lines.push("", "## KiCad", "");
    for (const entry of drift.kicad) {
      lines.push(`- ${kicadDriftMessage(entry)}`);
    }
  }

  if (drift.node.length > 0) {
    lines.push("", "## Node.js", "");
    for (const entry of drift.node) {
      lines.push(`- ${nodeDriftMessage(entry)}`);
    }
  }

  if (drift.cyclonedx.length > 0) {
    lines.push("", "## CycloneDX", "");
    for (const entry of drift.cyclonedx) {
      if (entry.reason === "schema-version-unreadable") {
        lines.push(`- CycloneDX schema version could not be read from ${entry.schemaUrl}; expected ${entry.expected}.`);
      } else {
        lines.push(
          `- CycloneDX schema reports ${entry.observed} but BoardReadyOps pins ${entry.expected} at ${entry.schemaUrl}.`,
        );
      }
    }
  }

  lines.push(
    "",
    "Next action: update `docs/compatibility.yaml`, regenerate `docs/support-matrix.md`, and extend CI if the new line is supported.",
  );
  return lines.join("\n");
}

export async function fetchNodeReleases(fetchImpl = globalThis.fetch) {
  return readJson(NODE_RELEASE_INDEX_URL, fetchImpl);
}

export async function fetchKicadReleaseTags(fetchImpl = globalThis.fetch) {
  const tags = await readJson(KICAD_TAGS_URL, fetchImpl);
  return tags.map((tag) => tag.name ?? tag.tag_name).filter(Boolean);
}

export async function fetchCycloneDxSchema(input, fetchImpl = globalThis.fetch) {
  const url = typeof input === "string" ? input : normalizeCompatibilityConfig(input).cyclonedx.schemaUrl;
  return readJson(url, fetchImpl);
}

export async function main(args = process.argv.slice(2), options = {}) {
  const [command = "render"] = args;
  const root = options.root ?? process.cwd();
  if (command === "render") {
    await renderCommand(root, args.slice(1));
    return;
  }
  if (command === "drift") {
    await driftCommand(root, args.slice(1), options.fetch);
    return;
  }
  throw new Error(`Unknown compatibility command: ${command}. Available commands: render, drift`);
}

async function renderCommand(root, args) {
  const compatibilityPath = path.resolve(root, optionValue(args, "--compatibility") ?? DEFAULT_COMPATIBILITY_PATH);
  const outputPath = path.resolve(root, optionValue(args, "--output") ?? DEFAULT_SUPPORT_MATRIX_PATH);
  const expected = renderSupportMatrix(yaml.load(await readFile(compatibilityPath, "utf8")));

  if (hasFlag(args, "--check")) {
    const current = await readFile(outputPath, "utf8");
    if (current !== expected) {
      throw new Error(`${path.relative(root, outputPath)} is stale. Run pnpm run compatibility:docs.`);
    }
    return;
  }

  await writeFile(outputPath, expected);
}

async function driftCommand(root, args, fetchImpl = globalThis.fetch) {
  const compatibilityPath = path.resolve(root, optionValue(args, "--compatibility") ?? DEFAULT_COMPATIBILITY_PATH);
  const markdownOutput = optionValue(args, "--markdown-output");
  const jsonOutput = optionValue(args, "--json-output");
  const githubOutput = optionValue(args, "--github-output");
  const config = yaml.load(await readFile(compatibilityPath, "utf8"));
  const [kicadReleases, nodeReleases, cycloneDxSchema] = await Promise.all([
    fetchKicadReleaseTags(fetchImpl),
    fetchNodeReleases(fetchImpl),
    fetchCycloneDxSchema(config, fetchImpl),
  ]);
  const drift = findCompatibilityDrift(config, { kicadReleases, nodeReleases, cycloneDxSchema });
  const report = buildDriftReport(drift);
  const driftFound = drift.kicad.length > 0 || drift.node.length > 0 || drift.cyclonedx.length > 0;

  if (markdownOutput) {
    await writeFile(path.resolve(root, markdownOutput), `${report}\n`);
  }
  if (jsonOutput) {
    await writeFile(path.resolve(root, jsonOutput), `${JSON.stringify({ driftFound, drift }, null, 2)}\n`);
  }
  if (githubOutput) {
    await writeFile(
      githubOutput,
      `drift=${driftFound ? "true" : "false"}\nissue_title=Compatibility matrix drift detected\n`,
      { flag: "a" },
    );
  }

  process.stdout.write(`${report}\n`);
}

function findKicadDrift(config, releases) {
  const latestBySeries = latestKicadReleasesBySeries(config, releases);
  return [
    ...untestedKicadSeriesDrift(config, latestBySeries),
    ...latestVerifiedKicadPatchDrift(config, latestBySeries),
  ];
}

function latestKicadReleasesBySeries(config, releases) {
  const minimum = parseSeries(config.kicad.minimum);
  const latestBySeries = new Map();
  for (const release of releases) {
    const version = stableReleaseName(releaseName(release));
    if (!version) {
      continue;
    }
    const series = `${version.major}.${version.minor}`;
    if (version.minor >= 90 || compareSeries(version, minimum) < 0) {
      continue;
    }
    const current = latestBySeries.get(series);
    if (!current || compareVersion(version, current) > 0) {
      latestBySeries.set(series, version);
    }
  }
  return latestBySeries;
}

function untestedKicadSeriesDrift(config, latestBySeries) {
  const tested = new Set(config.kicad.tested);
  const eol = new Set(config.kicad.eol);
  return [...latestBySeries.entries()]
    .sort(([left], [right]) => compareSeries(parseSeries(left), parseSeries(right)))
    .flatMap(([series, latest]) =>
      tested.has(series) || eol.has(series) ? [] : [{ series, latest: latest.normalized }],
    );
}

function latestVerifiedKicadPatchDrift(config, latestBySeries) {
  const latestVerified = stableReleaseName(config.kicad.latestVerified);
  if (!latestVerified) {
    return [
      {
        series: config.kicad.recommended,
        latest: config.kicad.latestVerified,
        tested: null,
        reason: "latest-verified-invalid",
      },
    ];
  }

  const latestRecommended = latestBySeries.get(config.kicad.recommended);
  if (!latestRecommended || compareVersion(latestRecommended, latestVerified) <= 0) {
    return [];
  }
  return [
    {
      series: config.kicad.recommended,
      latest: latestRecommended.normalized,
      tested: latestVerified.normalized,
      reason: "new-verified-patch",
    },
  ];
}

function findNodeDrift(config, releases) {
  const minimum = Number(config.node.minimum);
  const supported = new Set(config.node.supported);
  const documentedCurrent = new Set(config.node.current);
  const latestByMajor = new Map();
  for (const release of releases) {
    const version = stableReleaseName(releaseName(release));
    if (!version || version.major < minimum || version.major % 2 !== 0) {
      continue;
    }
    const major = String(version.major);
    const current = latestByMajor.get(major);
    if (!current || compareVersion(version, current.version) > 0) {
      latestByMajor.set(major, { version, lts: release.lts });
    }
  }

  const drift = [];
  for (const [major, entry] of [...latestByMajor.entries()].sort(([left], [right]) => Number(left) - Number(right))) {
    const latest = entry.version;
    if (!supported.has(major)) {
      const reason = unsupportedNodeReason(documentedCurrent.has(major), entry.lts);
      if (reason) {
        drift.push({ major, latest: latest.normalized, tested: null, reason });
      }
      continue;
    }
    const tested = config.node.tested[major];
    if (!tested) {
      drift.push({ major, latest: latest.normalized, tested: null, reason: "untested-supported" });
      continue;
    }
    const testedVersion = stableReleaseName(tested);
    if (!testedVersion || compareVersion(latest, testedVersion) <= 0) {
      continue;
    }
    const reason = latest.minor > testedVersion.minor ? "new-minor" : "new-release";
    drift.push({ major, latest: latest.normalized, tested: testedVersion.normalized, reason });
  }
  return drift;
}

function findCycloneDxDrift(config, schema) {
  if (!schema) {
    return [];
  }
  const observed = cycloneDxSchemaVersion(schema);
  if (!observed) {
    return [
      {
        expected: config.cyclonedx.specVersion,
        observed: null,
        schemaUrl: config.cyclonedx.schemaUrl,
        reason: "schema-version-unreadable",
      },
    ];
  }
  if (observed !== config.cyclonedx.specVersion) {
    return [
      {
        expected: config.cyclonedx.specVersion,
        observed,
        schemaUrl: config.cyclonedx.schemaUrl,
        reason: "schema-version-mismatch",
      },
    ];
  }
  return [];
}

function unsupportedNodeReason(isDocumentedCurrent, lts) {
  if (isDocumentedCurrent && lts === false) {
    return undefined;
  }
  if (isDocumentedCurrent && lts) {
    return "current-promoted-lts";
  }
  if (lts) {
    return "unsupported-lts";
  }
  return "undocumented-current";
}

function nodeDriftMessage(entry) {
  if (entry.reason === "undocumented-current") {
    return `Node.js ${entry.latest} is an even-numbered current line not documented under node.current.`;
  }
  if (entry.reason === "unsupported-lts") {
    return `Node.js ${entry.latest} is an LTS line not listed as supported.`;
  }
  if (entry.reason === "current-promoted-lts") {
    return `Node.js ${entry.latest} moved to LTS but is still documented only under node.current.`;
  }
  if (entry.reason === "untested-supported") {
    return `Node.js ${entry.major} is supported but has no tested latest version recorded.`;
  }
  return `Node.js ${entry.latest} is newer than recorded ${entry.tested} for supported major ${entry.major}.`;
}

function kicadDriftMessage(entry) {
  if (entry.reason === "new-verified-patch") {
    return `KiCad ${entry.latest} is newer than latest verified ${entry.tested} for recommended series ${entry.series}.`;
  }
  if (entry.reason === "latest-verified-invalid") {
    return `KiCad latest verified patch ${entry.latest} is not a stable major.minor.patch version.`;
  }
  return `KiCad ${entry.series} is not listed as CI-tested. Latest matching tag: ${entry.latest}.`;
}

function normalizeCompatibilityConfig(input) {
  const value = objectValue(input, "compatibility config");
  const kicad = objectValue(value.kicad, "kicad compatibility");
  const node = objectValue(value.node, "node compatibility");
  const cyclonedx = objectValue(value.cyclonedx, "cyclonedx compatibility");
  return {
    kicad: {
      minimum: stringValue(kicad.minimum, "kicad.minimum"),
      recommended: stringValue(kicad.recommended, "kicad.recommended"),
      latestVerified: stringValue(kicad.latestVerified, "kicad.latestVerified"),
      eol: stringArray(kicad.eol ?? [], "kicad.eol"),
      tested: stringArray(kicad.tested, "kicad.tested"),
      notes: stringRecord(kicad.notes ?? {}, "kicad.notes"),
    },
    node: {
      minimum: stringValue(node.minimum, "node.minimum"),
      minimumVersion: stringValue(node.minimumVersion ?? node.minimum, "node.minimumVersion"),
      recommended: stringValue(node.recommended, "node.recommended"),
      supported: stringArray(node.supported, "node.supported"),
      current: stringArray(node.current, "node.current"),
      tested: stringRecord(node.tested ?? {}, "node.tested"),
      policy: stringRecord(node.policy ?? {}, "node.policy"),
    },
    cyclonedx: {
      specVersion: stringValue(cyclonedx.specVersion, "cyclonedx.specVersion"),
      schemaUrl: stringValue(cyclonedx.schemaUrl, "cyclonedx.schemaUrl"),
      hbomSchema: stringValue(cyclonedx.hbomSchema, "cyclonedx.hbomSchema"),
      validation: stringValue(cyclonedx.validation, "cyclonedx.validation"),
    },
  };
}

function kicadNote(config, version) {
  const major = version.split(".")[0];
  return config.kicad.notes[version] ?? config.kicad.notes[`${major}.x`] ?? "";
}

function kicadLatestVerifiedCell(config, version) {
  return config.kicad.latestVerified.startsWith(`${version}.`) ? config.kicad.latestVerified : "";
}

function kicadMatrixVersions(config) {
  return [...new Set([...config.kicad.eol, ...config.kicad.tested])].sort((left, right) =>
    compareSeries(parseSeries(left), parseSeries(right)),
  );
}

function kicadSupportStatus(config, version) {
  if (version === config.kicad.recommended) {
    return "Recommended CI-tested line";
  }
  if (config.kicad.tested.includes(version)) {
    return "CI-tested line";
  }
  if (config.kicad.eol.includes(version) && version === config.kicad.minimum) {
    return "Minimum supported, upstream EOL, not CI-tested";
  }
  if (config.kicad.eol.includes(version)) {
    return "Upstream EOL, not CI-tested";
  }
  return "Supported";
}

function nodeSupportStatus(config, version) {
  if (version === config.node.minimum) {
    return "Minimum supported runtime";
  }
  if (version === config.node.recommended) {
    return "Recommended Active LTS runtime";
  }
  return "Supported LTS runtime";
}

function markdownCell(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}

function releaseName(value) {
  if (typeof value === "string") {
    return value;
  }
  if (value && typeof value === "object") {
    return value.version ?? value.name ?? value.tag_name ?? "";
  }
  return "";
}

function stableReleaseName(value) {
  const match = String(value).match(/^v?(\d+)\.(\d+)\.(\d+)$/);
  if (!match) {
    return undefined;
  }
  const [, major, minor, patch] = match;
  return {
    major: Number(major),
    minor: Number(minor),
    patch: Number(patch),
    normalized: `${major}.${minor}.${patch}`,
  };
}

function cycloneDxSchemaVersion(schema) {
  const value = objectValue(schema, "CycloneDX schema");
  const id = typeof value.$id === "string" ? value.$id : typeof value.id === "string" ? value.id : "";
  const idMatch = id.match(/bom-(\d+\.\d+)\.schema\.json/);
  if (idMatch) {
    return idMatch[1];
  }
  const properties = value.properties && typeof value.properties === "object" ? value.properties : {};
  const specVersion =
    properties.specVersion && typeof properties.specVersion === "object" ? properties.specVersion : {};
  const candidates = [
    specVersion.const,
    ...(Array.isArray(specVersion.enum) ? specVersion.enum : []),
    ...(Array.isArray(specVersion.examples) ? specVersion.examples : []),
  ];
  return candidates.find((candidate) => typeof candidate === "string" && /^\d+\.\d+$/.test(candidate));
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  await main();
}
