import { boardReadyVersion } from "../generated/version.js";

export interface HandoffProfileSummary {
  id: string;
  name: string;
  service: string;
  requiredOutputs: string[];
  assumptions: string[];
  caveats: string[];
}

interface HandoffFile {
  output: string;
  source: string;
  target: string;
}

interface HandoffPlan {
  files: HandoffFile[];
  includedOutputs: string[];
  missingOutputs: string[];
}

export interface HandoffManifestFile extends HandoffFile {
  sha256: string;
  bytes: number;
}

interface HandoffManifest {
  schemaVersion: 1;
  tool: { name: "boardreadyops"; version: string };
  generatedAt: string;
  vendor: { id: string; name: string; service: string };
  decision: { status: "ready" | "incomplete"; missingOutputs: string[] };
  requiredOutputs: string[];
  includedOutputs: string[];
  assumptions: string[];
  files: HandoffManifestFile[];
}

const OUTPUT_DIRECTORIES: Record<string, string> = {
  gerber: "gerbers",
  drill: "drill",
  bom: "bom",
  position: "assembly",
  pdf: "documentation",
  step: "documentation",
};

function outputDirectory(kind: string): string {
  return OUTPUT_DIRECTORIES[kind] ?? "other";
}

function baseName(source: string): string {
  const segments = source.split("/");
  return segments[segments.length - 1] ?? source;
}

/**
 * Build a deterministic handoff layout. Each discovered source file is assigned
 * to exactly one output kind (required kinds first, then any extras) so a file
 * is never copied twice, and target paths are disambiguated on collision.
 */
export function planHandoffPackage(outputs: Record<string, string[]>, profile: HandoffProfileSummary): HandoffPlan {
  const orderedKinds = [
    ...profile.requiredOutputs,
    ...Object.keys(outputs)
      .filter((kind) => !profile.requiredOutputs.includes(kind))
      .sort(),
  ];
  const assignedSources = new Set<string>();
  const usedTargets = new Set<string>();
  const present = new Set<string>();
  const files: HandoffFile[] = [];
  for (const kind of orderedKinds) {
    for (const source of [...(outputs[kind] ?? [])].sort((left, right) => left.localeCompare(right))) {
      if (assignedSources.has(source)) {
        continue;
      }
      assignedSources.add(source);
      present.add(kind);
      files.push({ output: kind, source, target: uniqueTarget(outputDirectory(kind), baseName(source), usedTargets) });
    }
  }
  files.sort((left, right) => left.target.localeCompare(right.target) || left.source.localeCompare(right.source));
  return {
    files,
    includedOutputs: [...present].sort(),
    missingOutputs: profile.requiredOutputs.filter((kind) => !present.has(kind)).sort(),
  };
}

function uniqueTarget(directory: string, name: string, used: Set<string>): string {
  const dot = name.lastIndexOf(".");
  const stem = dot > 0 ? name.slice(0, dot) : name;
  const extension = dot > 0 ? name.slice(dot) : "";
  let candidate = `${directory}/${name}`;
  let counter = 2;
  while (used.has(candidate)) {
    candidate = `${directory}/${stem}-${counter}${extension}`;
    counter += 1;
  }
  used.add(candidate);
  return candidate;
}

export function buildHandoffManifest(
  profile: HandoffProfileSummary,
  plan: HandoffPlan,
  files: HandoffManifestFile[],
  generatedAt: string,
): HandoffManifest {
  return {
    schemaVersion: 1,
    tool: { name: "boardreadyops", version: boardReadyVersion },
    generatedAt,
    vendor: { id: profile.id, name: profile.name, service: profile.service },
    decision: {
      status: plan.missingOutputs.length === 0 ? "ready" : "incomplete",
      missingOutputs: plan.missingOutputs,
    },
    requiredOutputs: [...profile.requiredOutputs].sort(),
    includedOutputs: plan.includedOutputs,
    assumptions: profile.assumptions,
    files: [...files].sort((left, right) => left.target.localeCompare(right.target)),
  };
}

export function renderHandoffReadme(profile: HandoffProfileSummary, plan: HandoffPlan, generatedAt: string): string {
  const lines: string[] = [];
  lines.push(`# ${profile.name} manufacturer handoff package`);
  lines.push("");
  lines.push(`Generated by BoardReadyOps ${boardReadyVersion} on ${generatedAt}.`);
  lines.push("");
  lines.push(`- Vendor profile: \`${profile.id}\` (${profile.name})`);
  lines.push(`- Service: ${profile.service}`);
  lines.push(
    `- Status: ${plan.missingOutputs.length === 0 ? "ready" : `incomplete (missing ${plan.missingOutputs.join(", ")})`}`,
  );
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  if (plan.files.length === 0) {
    lines.push("No manufacturing outputs were discovered for this package.");
  } else {
    lines.push("| Output | File |");
    lines.push("| --- | --- |");
    for (const file of plan.files) {
      lines.push(`| ${file.output} | \`${file.target}\` |`);
    }
  }
  if (plan.missingOutputs.length > 0) {
    lines.push("");
    lines.push("## Missing required outputs");
    lines.push("");
    lines.push("The following outputs are required by this vendor profile but were not found:");
    lines.push("");
    for (const output of plan.missingOutputs) {
      lines.push(`- ${output}`);
    }
  }
  if (profile.assumptions.length > 0) {
    lines.push("");
    lines.push("## Assumptions");
    lines.push("");
    for (const assumption of profile.assumptions) {
      lines.push(`- ${assumption}`);
    }
  }
  if (profile.caveats.length > 0) {
    lines.push("");
    lines.push("## Caveats");
    lines.push("");
    for (const caveat of profile.caveats) {
      lines.push(`- ${caveat}`);
    }
  }
  return `${lines.join("\n")}\n`;
}
